from typing import Protocol

from stepik_autopilot.application.dto import (
    AttemptDTO,
    BatchCommitDTO,
    BatchDTO,
    ChoiceReplyDTO,
    CourseContentDTO,
    CoursePageDTO,
    ItemDTO,
    NextBatchStateDTO,
    OperationDTO,
    RemoteSubmissionDTO,
    RunControlDTO,
    RunDTO,
    RunStartedDTO,
    SubmissionDTO,
    TaskDTO,
)
from stepik_autopilot.core.enums import ItemState, OperationState, RunState


class IdempotencyRepository(Protocol):
    async def get_start(self, account_id: str, request_id: str, payload_hash: str) -> RunStartedDTO | None: ...
    async def save_start(self, account_id: str, request_id: str, payload_hash: str, value: RunStartedDTO) -> None: ...
    async def get_next(
        self, account_id: str, request_id: str, payload_hash: str
    ) -> BatchDTO | NextBatchStateDTO | None: ...
    async def save_next(
        self, account_id: str, request_id: str, payload_hash: str, value: BatchDTO | NextBatchStateDTO
    ) -> None: ...
    async def get_commit(self, account_id: str, request_id: str, payload_hash: str) -> BatchCommitDTO | None: ...
    async def save_commit(self, account_id: str, request_id: str, payload_hash: str, value: BatchCommitDTO) -> None: ...
    async def get_control(self, account_id: str, request_id: str, payload_hash: str) -> RunControlDTO | None: ...
    async def save_control(self, account_id: str, request_id: str, payload_hash: str, value: RunControlDTO) -> None: ...


class RunRepository(Protocol):
    async def get_run(self, account_id: str, run_id: str) -> RunDTO | None: ...
    async def create_run(self, run: RunDTO) -> None: ...
    async def set_run_state(self, account_id: str, run_id: str, state: RunState) -> None: ...


class ItemRepository(Protocol):
    async def add_items(self, items: tuple[ItemDTO, ...]) -> None: ...
    async def list_items(
        self, account_id: str, run_id: str, states: frozenset[ItemState] | None = None
    ) -> tuple[ItemDTO, ...]: ...
    async def get_item(self, account_id: str, run_id: str, item_id: str) -> ItemDTO | None: ...
    async def save_item(self, account_id: str, item: ItemDTO) -> None: ...


class BatchRepository(Protocol):
    async def create_batch(self, run_id: str, batch_id: str) -> None: ...
    async def active_batch(self, account_id: str, run_id: str) -> str | None: ...
    async def close_batch(self, run_id: str, batch_id: str) -> None: ...


class SubmissionRepository(Protocol):
    async def list_submissions(self, account_id: str, run_id: str) -> tuple[SubmissionDTO, ...]: ...
    async def get_submission(self, account_id: str, run_id: str, submission_id: str) -> SubmissionDTO | None: ...
    async def create_submission(self, submission: SubmissionDTO) -> None: ...
    async def update_submission(self, submission: SubmissionDTO) -> None: ...


class OperationRepository(Protocol):
    async def create_operation(self, operation: OperationDTO) -> None: ...
    async def update_operation(
        self, operation_id: str, state: OperationState, upstream_id: str | None = None
    ) -> None: ...
    async def unresolved_operations(self, account_id: str, run_id: str) -> tuple[OperationDTO, ...]: ...


class StepikAccountGateway(Protocol):
    async def current_account(self) -> str: ...


class StepikCourseGateway(Protocol):
    async def courses(self, query: str | None, enrolled_only: bool, cursor: int, limit: int) -> CoursePageDTO: ...
    async def content(
        self,
        course_id: str,
        explicit_step_ids: tuple[str, ...] | None = None,
        section_numbers: tuple[int, ...] | None = None,
    ) -> CourseContentDTO: ...


class StepikAttemptGateway(Protocol):
    async def prepare_attempt(self, task: TaskDTO) -> AttemptDTO: ...


class StepikSubmissionGateway(Protocol):
    async def submit(self, attempt_id: str, reply: ChoiceReplyDTO) -> RemoteSubmissionDTO: ...
    async def submissions(self, ids: tuple[str, ...]) -> tuple[RemoteSubmissionDTO, ...]: ...
    async def find_submission(self, attempt_id: str, reply_hash: str) -> RemoteSubmissionDTO | None: ...
